### PR TITLE
Added 2 additional Telegram addresses.

### PR DESCRIPTION
**Pull request by 54m4d**
Just note that the script only works on the K version though.

### CODE REVIEW

**Comment by Neet-Nestor** [comment]
LGTM. Thanks for the contribution. I only used the [https://web.telegram.org/k/](https://web.telegram.org/k/) url before and didn't notice there are other urls for the webapp.

**Comment by 54m4d** [comment]
Thanks!

**Comment by 54m4d** [comment]
BTW, are you able to dl with IDM? it only downloads directly in the browser, but maybe it has something to do with blob, i'm not sure.

**Comment by Neet-Nestor** [comment]
> BTW, are you able to dl with IDM? it only downloads directly in the browser, but maybe it has something to do with blob, i'm not sure.

Could you please elaborate more on IDM? I never used it before and don't know much about it.

Feel free to add related functionality if you think it's possible and you'd like to! :shipit:

**Comment by 54m4d** [comment]
[IDM](https://www.internetdownloadmanager.com/) Is the popular download manager, but any dl manager can be tested, it shoud work out of the box.

**Pull request merged**
